-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-04-08 18:55:38 EDT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE na_booking (
    booking_id    NUMBER(10) NOT NULL,
    pickup_locid  NUMBER(10) NOT NULL,
    pickup_date   DATE NOT NULL,
    dropoff_date  DATE NOT NULL,
    dropoff_locid NUMBER(10) NOT NULL,
    odo_start     NUMBER(10, 2) NOT NULL,
    odo_end       NUMBER(10, 2) NOT NULL,
    odo_limit     NUMBER(10, 2) NOT NULL,
    vin           VARCHAR2(17) NOT NULL,
    cust_id       NUMBER(10) NOT NULL,
    coup_id       VARCHAR2(10)
);

COMMENT ON COLUMN na_booking.booking_id IS
    'This is the unique identifier of a vehicle booking.';

COMMENT ON COLUMN na_booking.pickup_locid IS
    'This is the unique identifier from LOCATION entity.';

COMMENT ON COLUMN na_booking.pickup_date IS
    'Pick up date of the vehicle.';

COMMENT ON COLUMN na_booking.dropoff_date IS
    'Drop off date of the vehicle.';

COMMENT ON COLUMN na_booking.dropoff_locid IS
    'This is the unique identifier from LOCATION entity.';

COMMENT ON COLUMN na_booking.odo_start IS
    'Odometer reading when the vehicle is handed over to the cutomer.';

COMMENT ON COLUMN na_booking.odo_end IS
    'Odometer reading when the vehicle is handed over to WOW by customer.';

COMMENT ON COLUMN na_booking.odo_limit IS
    'Daily Odometer Limit for the vehicle rental service.';

COMMENT ON COLUMN na_booking.vin IS
    'This is the unique identifier from LOC_VCLASS entity.';

COMMENT ON COLUMN na_booking.cust_id IS
    'This is the unique identifier from CUSTOMER entity.';

COMMENT ON COLUMN na_booking.coup_id IS
    'This is the unique identifier from COUPON entity.';

ALTER TABLE na_booking ADD CONSTRAINT na_booking_pk PRIMARY KEY ( booking_id );

CREATE TABLE na_company (
    comp_id    NUMBER(10) NOT NULL,
    comp_name  VARCHAR2(30) NOT NULL,
    comp_regno VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN na_company.comp_id IS
    'This is the unique identifier of a corporation.
';

COMMENT ON COLUMN na_company.comp_name IS
    'Name of the corporation.';

COMMENT ON COLUMN na_company.comp_regno IS
    'Registarion number of corporation.';

ALTER TABLE na_company ADD CONSTRAINT na_company_pk PRIMARY KEY ( comp_id );

CREATE TABLE na_corp (
    cust_id NUMBER(10) NOT NULL,
    emp_no  NUMBER(10) NOT NULL,
    comp_id NUMBER(10) NOT NULL
);

COMMENT ON COLUMN na_corp.cust_id IS
    'This is the unique identifier of a customer.';

COMMENT ON COLUMN na_corp.emp_no IS
    'This is the unique identifier of a employee in corporation.';

ALTER TABLE na_corp ADD CONSTRAINT na_corp_pk PRIMARY KEY ( cust_id );

ALTER TABLE na_corp ADD CONSTRAINT na_corp_pkv1 UNIQUE ( emp_no );

CREATE TABLE na_coup (
    coup_id        VARCHAR2(10) NOT NULL,
    coup_name      VARCHAR2(30) NOT NULL,
    coup_percent   NUMBER(4, 2) NOT NULL,
    coup_startdate DATE NOT NULL,
    coup_enddate   DATE NOT NULL
);

COMMENT ON COLUMN na_coup.coup_id IS
    'This is the unique identifier of a coupon.';

COMMENT ON COLUMN na_coup.coup_name IS
    'This is the name of the coupon.';

COMMENT ON COLUMN na_coup.coup_percent IS
    'This is the percentage of discount on a coupon.';

COMMENT ON COLUMN na_coup.coup_startdate IS
    'Start date of a coupon.';

COMMENT ON COLUMN na_coup.coup_enddate IS
    'This is the expiration date of a coupon.';

ALTER TABLE na_coup ADD CONSTRAINT na_coup_pk PRIMARY KEY ( coup_id );

CREATE TABLE na_cust (
    cust_id  NUMBER(10) NOT NULL,
    fname    VARCHAR2(30) NOT NULL,
    lname    VARCHAR2(30) NOT NULL,
    cphno    NUMBER(10) NOT NULL,
    cemailid VARCHAR2(30) NOT NULL,
    cstreet1 VARCHAR2(30) NOT NULL,
    cstreet2 VARCHAR2(30),
    ccity    VARCHAR2(30) NOT NULL,
    cstate   VARCHAR2(30) NOT NULL,
    czipcode VARCHAR2(6) NOT NULL,
    ccountry VARCHAR2(30) NOT NULL,
    ctype    CHAR(1) NOT NULL
);

ALTER TABLE na_cust
    ADD CONSTRAINT ch_inh_na_cust CHECK ( ctype IN ( 'C', 'I' ) );

COMMENT ON COLUMN na_cust.cust_id IS
    'This is the unique identifier of a customer.';

COMMENT ON COLUMN na_cust.fname IS
    'First name of a customer.';

COMMENT ON COLUMN na_cust.lname IS
    'Last name of a customer.';

COMMENT ON COLUMN na_cust.cphno IS
    'Phone number details of the customer.';

COMMENT ON COLUMN na_cust.cemailid IS
    'Email Id details of the customer.';

COMMENT ON COLUMN na_cust.cstreet1 IS
    'Street1 details of a customer.';

COMMENT ON COLUMN na_cust.cstreet2 IS
    'Street2 details of a customer.';

COMMENT ON COLUMN na_cust.ccity IS
    'City details of the customer.';

COMMENT ON COLUMN na_cust.cstate IS
    'State details of the customer.';

COMMENT ON COLUMN na_cust.czipcode IS
    'Zipcode details of the customer.';

COMMENT ON COLUMN na_cust.ccountry IS
    'Country details of the customer.';

COMMENT ON COLUMN na_cust.ctype IS
    'This is the discriminator of a customer.';

ALTER TABLE na_cust ADD CONSTRAINT na_cust_pk PRIMARY KEY ( cust_id );

CREATE TABLE na_cust_coup (
    cust_id   NUMBER(10) NOT NULL,
    coup_id   VARCHAR2(10) NOT NULL,
    coup_type VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN na_cust_coup.cust_id IS
    'This is the unique identifier from CUSTOMER entity.';

COMMENT ON COLUMN na_cust_coup.coup_id IS
    'This is the unique identifier from COUPON entity.';

COMMENT ON COLUMN na_cust_coup.coup_type IS
    'This is the type of coupon (Individual or Corporate).';

ALTER TABLE na_cust_coup ADD CONSTRAINT na_cust_coup_pk PRIMARY KEY ( coup_id,
                                                                      cust_id );

CREATE TABLE na_indiv (
    cust_id      NUMBER(10) NOT NULL,
    driver_licno VARCHAR2(10) NOT NULL,
    ins_plcyno   VARCHAR2(10) NOT NULL,
    ins_compname VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN na_indiv.cust_id IS
    'This is the unique identifier of a customer.';

COMMENT ON COLUMN na_indiv.driver_licno IS
    'This is the driver license number.';

COMMENT ON COLUMN na_indiv.ins_plcyno IS
    'This is the insurance policy number of a customer.';

COMMENT ON COLUMN na_indiv.ins_compname IS
    'This is insurance company name.';

ALTER TABLE na_indiv ADD CONSTRAINT na_indiv_pk PRIMARY KEY ( cust_id );

ALTER TABLE na_indiv ADD CONSTRAINT na_indiv_pkv1 UNIQUE ( driver_licno );

CREATE TABLE na_invoice (
    inv_id     NUMBER(10) NOT NULL,
    inv_date   DATE NOT NULL,
    inv_amt    NUMBER(10, 2) NOT NULL,
    booking_id NUMBER(10) NOT NULL
);

COMMENT ON COLUMN na_invoice.inv_id IS
    'This is the unique identifier of an invoice.';

COMMENT ON COLUMN na_invoice.inv_date IS
    'This is the date of an invoice.';

COMMENT ON COLUMN na_invoice.inv_amt IS
    'This is the invoice amount.';

COMMENT ON COLUMN na_invoice.booking_id IS
    'This is the unique identifier from Booking entity.';

CREATE UNIQUE INDEX na_invoice__idx ON
    na_invoice (
        booking_id
    ASC );

ALTER TABLE na_invoice ADD CONSTRAINT na_invoice_pk PRIMARY KEY ( inv_id );

ALTER TABLE na_invoice ADD CONSTRAINT na_invoice_pk PRIMARY KEY ( inv_id );
CREATE SEQUENCE name_of_sequence
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;

CREATE TABLE na_loc (
    loc_id   NUMBER(10) NOT NULL,
    lname    VARCHAR2(30) NOT NULL,
    lemailid VARCHAR2(30) NOT NULL,
    lphno    NUMBER(10) NOT NULL,
    lstreet1 VARCHAR2(30) NOT NULL,
    lstreet2 VARCHAR2(30),
    lcity    VARCHAR2(30) NOT NULL,
    lstate   VARCHAR2(30) NOT NULL,
    lzipcode VARCHAR2(6) NOT NULL,
    lcountry VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN na_loc.loc_id IS
    'This is the unique identifier of the office location.';

COMMENT ON COLUMN na_loc.lname IS
    'Name of the office location.';

COMMENT ON COLUMN na_loc.lemailid IS
    'Email Id details of the office location.';

COMMENT ON COLUMN na_loc.lphno IS
    'Phone number of the office location.';

COMMENT ON COLUMN na_loc.lstreet1 IS
    'Street 1 details of the office location.';

COMMENT ON COLUMN na_loc.lstreet2 IS
    'Street 2 details of the office location.';

COMMENT ON COLUMN na_loc.lcity IS
    'City details of the office location.';

COMMENT ON COLUMN na_loc.lstate IS
    'State details of the office location.';

COMMENT ON COLUMN na_loc.lzipcode IS
    'Zip code details of the office location.';

COMMENT ON COLUMN na_loc.lcountry IS
    'Country details of the office location.';

ALTER TABLE na_loc ADD CONSTRAINT na_loc_pk PRIMARY KEY ( loc_id );

CREATE TABLE na_loc_vclass (
    vin       VARCHAR2(17) NOT NULL,
    make      VARCHAR2(30) NOT NULL,
    model     VARCHAR2(30) NOT NULL,
    year      NUMBER(4) NOT NULL,
    lic_plate VARCHAR2(10) NOT NULL,
    loc_id    NUMBER(10) NOT NULL,
    vclass_id NUMBER(10) NOT NULL
);

COMMENT ON COLUMN na_loc_vclass.vin IS
    'This is Vehicle Identification Number (VIN).';

COMMENT ON COLUMN na_loc_vclass.make IS
    'Make details of the vehicle.';

COMMENT ON COLUMN na_loc_vclass.model IS
    'Model details of the vehicle.';

COMMENT ON COLUMN na_loc_vclass.year IS
    'Vehicle release year details.';

COMMENT ON COLUMN na_loc_vclass.lic_plate IS
    'License plate number of the vehicle.';

COMMENT ON COLUMN na_loc_vclass.loc_id IS
    'This is the unique identifier from LOCATION entity.';

COMMENT ON COLUMN na_loc_vclass.vclass_id IS
    'This is the unique identifier from VCLASS entity.';

ALTER TABLE na_loc_vclass ADD CONSTRAINT na_loc_vclass_pk PRIMARY KEY ( vin );

CREATE TABLE na_payment (
    pay_id     NUMBER(10) NOT NULL,
    pay_date   DATE NOT NULL,
    pay_amt    NUMBER(10, 2) NOT NULL,
    pay_method VARCHAR2(30) NOT NULL,
    card_no    NUMBER(16) NOT NULL,
    inv_id     NUMBER(10) NOT NULL
);

COMMENT ON COLUMN na_payment.pay_id IS
    'This is the unique identifier of a payment.';

COMMENT ON COLUMN na_payment.pay_date IS
    'Date of the payment.';

COMMENT ON COLUMN na_payment.pay_amt IS
    'This is the payment amount.';

COMMENT ON COLUMN na_payment.pay_method IS
    'Method of payment details.';

COMMENT ON COLUMN na_payment.card_no IS
    'Details of card number through which payment has been made.';

COMMENT ON COLUMN na_payment.inv_id IS
    'This is the unique identifier from INVOICE entity.';

ALTER TABLE na_payment ADD CONSTRAINT na_payment_pk PRIMARY KEY ( pay_id );

CREATE TABLE na_vclass (
    vclass_id   NUMBER(10) NOT NULL,
    vclass_name VARCHAR2(30) NOT NULL,
    rate        NUMBER(9, 2) NOT NULL,
    over_fee    NUMBER(9, 2) NOT NULL
);

COMMENT ON COLUMN na_vclass.vclass_id IS
    'This is the unique identifier of vehicle class.';

COMMENT ON COLUMN na_vclass.vclass_name IS
    'This is the name for a vehicle class.';

COMMENT ON COLUMN na_vclass.rate IS
    'This is the rental rate of a vehicle class per day.';

COMMENT ON COLUMN na_vclass.over_fee IS
    'This is over mileage fees.';

ALTER TABLE na_vclass ADD CONSTRAINT na_vclass_pk PRIMARY KEY ( vclass_id );

ALTER TABLE na_booking
    ADD CONSTRAINT na_booking_na_coup_fk FOREIGN KEY ( coup_id )
        REFERENCES na_coup ( coup_id );

ALTER TABLE na_booking
    ADD CONSTRAINT na_booking_na_cust_fk FOREIGN KEY ( cust_id )
        REFERENCES na_cust ( cust_id );

ALTER TABLE na_booking
    ADD CONSTRAINT na_booking_na_loc_fk FOREIGN KEY ( dropoff_locid )
        REFERENCES na_loc ( loc_id );

ALTER TABLE na_booking
    ADD CONSTRAINT na_booking_na_loc_fkv2 FOREIGN KEY ( pickup_locid )
        REFERENCES na_loc ( loc_id );

ALTER TABLE na_booking
    ADD CONSTRAINT na_booking_na_loc_vclass_fk FOREIGN KEY ( vin )
        REFERENCES na_loc_vclass ( vin );

ALTER TABLE na_corp
    ADD CONSTRAINT na_corp_na_company_fk FOREIGN KEY ( comp_id )
        REFERENCES na_company ( comp_id );

ALTER TABLE na_corp
    ADD CONSTRAINT na_corp_na_cust_fk FOREIGN KEY ( cust_id )
        REFERENCES na_cust ( cust_id );

ALTER TABLE na_cust_coup
    ADD CONSTRAINT na_cust_coup_na_coup_fk FOREIGN KEY ( coup_id )
        REFERENCES na_coup ( coup_id );

ALTER TABLE na_cust_coup
    ADD CONSTRAINT na_cust_coup_na_cust_fk FOREIGN KEY ( cust_id )
        REFERENCES na_cust ( cust_id );

ALTER TABLE na_indiv
    ADD CONSTRAINT na_indiv_na_cust_fk FOREIGN KEY ( cust_id )
        REFERENCES na_cust ( cust_id );

ALTER TABLE na_invoice
    ADD CONSTRAINT na_invoice_na_booking_fk FOREIGN KEY ( booking_id )
        REFERENCES na_booking ( booking_id );

ALTER TABLE na_loc_vclass
    ADD CONSTRAINT na_loc_vclass_na_loc_fk FOREIGN KEY ( loc_id )
        REFERENCES na_loc ( loc_id );

ALTER TABLE na_loc_vclass
    ADD CONSTRAINT na_loc_vclass_na_vclass_fk FOREIGN KEY ( vclass_id )
        REFERENCES na_vclass ( vclass_id );

ALTER TABLE na_payment
    ADD CONSTRAINT na_payment_na_invoice_fk FOREIGN KEY ( inv_id )
        REFERENCES na_invoice ( inv_id );

CREATE OR REPLACE TRIGGER arc_fkarc_2_na_indiv BEFORE
    INSERT OR UPDATE OF cust_id ON na_indiv
    FOR EACH ROW
DECLARE
    d CHAR(1);
BEGIN
    SELECT
        a.ctype
    INTO d
    FROM
        na_cust a
    WHERE
        a.cust_id = :new.cust_id;

    IF ( d IS NULL OR d <> 'I' ) THEN
        raise_application_error(
                               -20223,
                               'FK NA_INDIV_NA_CUST_FK in Table NA_INDIV violates Arc constraint on Table NA_CUST - discriminator column CTYPE doesn''t have value ''I'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_2_na_corp BEFORE
    INSERT OR UPDATE OF cust_id ON na_corp
    FOR EACH ROW
DECLARE
    d CHAR(1);
BEGIN
    SELECT
        a.ctype
    INTO d
    FROM
        na_cust a
    WHERE
        a.cust_id = :new.cust_id;

    IF ( d IS NULL OR d <> 'C' ) THEN
        raise_application_error(
                               -20223,
                               'FK NA_CORP_NA_CUST_FK in Table NA_CORP violates Arc constraint on Table NA_CUST - discriminator column CTYPE doesn''t have value ''C'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             1
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           2
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
